// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Demo.Common;

namespace Demo.Entities;

public class Company : BaseTable
{
	public string Name { get; set; } = default!;
	public string Code { get; set; } = default!;
	public string? Address { get; set; };
	public bool IsActive { get; set; } = true;

	public ICollection<Employee> Employees { get; set; } = [];
	public ICollection<Department> Departments { get; set; } = [];
}

public class CompanyConfiguration : IEntityTypeConfiguration<Company>
{
	public void Configure(EntityTypeBuilder<Company> builder)
	{
		builder.Property(c => c.Name).IsRequired().HasMaxLength(100);
		builder.Property(c => c.Code).IsRequired().HasMaxLength(20);
		builder.Property(c => c.Address).HasMaxLength(255);

		builder.HasIndex(c => c.Name, c => c.Code).IsUnique();
	}
}
