// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Testing.Conventions;

namespace Generated;

public class Customer : BaseTable
{
	public string FirstName { get; set; } = default!;
	public string LastName { get; set; } = default!;
	public string? Email { get; set; };
	public string? Address { get; set; };
	public decimal Balance { get; set; };
	public bool IsActive { get; set; } = true;

	public ICollection<Order> Orders { get; set; } = [];
}

public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
	public void Configure(EntityTypeBuilder<Customer> builder)
	{
		builder.Property(c => c.FirstName).IsRequired().HasMaxLength(50);
		builder.Property(c => c.LastName).IsRequired().HasMaxLength(50);
		builder.Property(c => c.Email).HasMaxLength(50);
		builder.Property(c => c.Address).HasMaxLength(50);
	}
}
