// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Demo.Common;

namespace Demo.Entities;

public class Department : BaseTable
{
	public int CompanyId { get; set; };
	public string Name { get; set; } = default!;
	public decimal Budget { get; set; } = 0;
	public int ManagerId { get; set; };

	public Company? Company { get; set; }
}

public class DepartmentConfiguration : IEntityTypeConfiguration<Department>
{
	public void Configure(EntityTypeBuilder<Department> builder)
	{
		builder.Property(d => d.Name).IsRequired().HasMaxLength(50);

		builder.HasOne(d => d.Company)
			.WithMany(e => e.Departments)
			.HasForeignKey(d => d.CompanyId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasOne(d => d.Manager)
			.WithMany(e => e.Departments)
			.HasForeignKey(d => d.ManagerId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(d => d.Name).IsUnique();
	}
}
