// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Demo.Common;

namespace Demo.Entities;

public class Employee : BaseTable
{
	public int CompanyId { get; set; };
	public string Email { get; set; } = default!;
	public string FirstName { get; set; } = default!;
	public string LastName { get; set; } = default!;
	public decimal? Salary { get; set; };
	public DateTime HireDate { get; set; };

	public Company? Company { get; set; }
}

public class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
	public void Configure(EntityTypeBuilder<Employee> builder)
	{
		builder.Property(e => e.Email).IsRequired().HasMaxLength(100);
		builder.Property(e => e.FirstName).IsRequired().HasMaxLength(50);
		builder.Property(e => e.LastName).IsRequired().HasMaxLength(50);

		builder.HasOne(e => e.Company)
			.WithMany(e => e.Employees)
			.HasForeignKey(e => e.CompanyId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(e => e.Email).IsUnique();
	}
}
