// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Testing.Conventions;

namespace Generated;

public class Status : BaseTable
{
	public string Name { get; set; } = default!;
	public string? Description { get; set; };

	public ICollection<Order> Orders { get; set; } = [];
}

public class StatusConfiguration : IEntityTypeConfiguration<Status>
{
	public void Configure(EntityTypeBuilder<Status> builder)
	{
		builder.Property(s => s.Name).IsRequired().HasMaxLength(50);
		builder.Property(s => s.Description).HasMaxLength(255);
	}
}
